---
- name: Nginx | Modules | Make sure the naxsi_module configuration is up to date
  copy:
    src: ../../files/naxsi_core.rules
    dest: "{{nginx_dir}}/naxsi_core.rules"
    owner: root
    group: root
    mode: 0644
