---
- name: Nginx | Modules | Make sure the upload_progress_module configuration is updated
  template:
    src: ../../templates/modules/upload_progress.j2
    dest: "{{nginx_dir}}/sites-available/upload_progress"
    owner: root
    group: root
    mode: 0644
