# file: nginx/handlers/main.yml

- name:    restart nginx
  service: name=nginx state=restarted
  sudo:    yes

- name:    reload nginx
  service: name=nginx state=reloaded
  sudo:    yes

- name:    restart monit
  service: name=monit state=restarted
  sudo:    yes
